/* tslint:disable */
/* eslint-disable */
/**
 * Momocraft Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiErrorDto
 */
export interface ApiErrorDto {
    /**
     * 
     * @type {number}
     * @memberof ApiErrorDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorDto
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorDto
     */
    error: string;
}

export function ApiErrorDtoFromJSON(json: any): ApiErrorDto {
    return ApiErrorDtoFromJSONTyped(json, false);
}

export function ApiErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': json['error'],
    };
}

export function ApiErrorDtoToJSON(value?: ApiErrorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'message': value.message,
        'error': value.error,
    };
}


