/* tslint:disable */
/* eslint-disable */
/**
 * Momocraft Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthGoogleRequestDto
 */
export interface OAuthGoogleRequestDto {
    /**
     * 
     * @type {string}
     * @memberof OAuthGoogleRequestDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthGoogleRequestDto
     */
    redirectUrl: string;
}

export function OAuthGoogleRequestDtoFromJSON(json: any): OAuthGoogleRequestDto {
    return OAuthGoogleRequestDtoFromJSONTyped(json, false);
}

export function OAuthGoogleRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthGoogleRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'redirectUrl': json['redirectUrl'],
    };
}

export function OAuthGoogleRequestDtoToJSON(value?: OAuthGoogleRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'redirectUrl': value.redirectUrl,
    };
}


