/* tslint:disable */
/* eslint-disable */
/**
 * Momocraft Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OAuthRequestDto
 */
export interface OAuthRequestDto {
  /**
   *
   * @type {string}
   * @memberof OAuthRequestDto
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof OAuthRequestDto
   */
  redirectUrl: string;
}

export function OAuthRequestDtoFromJSON(json: any): OAuthRequestDto {
  return OAuthRequestDtoFromJSONTyped(json, false);
}

export function OAuthRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthRequestDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json['code'],
    redirectUrl: json['redirectUrl'],
  };
}

export function OAuthRequestDtoToJSON(value?: OAuthRequestDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    redirectUrl: value.redirectUrl,
  };
}
