/* tslint:disable */
/* eslint-disable */
/**
 * Momocraft Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ItemCollectionDto,
    ItemCollectionDtoFromJSON,
    ItemCollectionDtoFromJSONTyped,
    ItemCollectionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserCollectionListDto
 */
export interface UserCollectionListDto {
    /**
     * 
     * @type {Array<ItemCollectionDto>}
     * @memberof UserCollectionListDto
     */
    collections: Array<ItemCollectionDto>;
}

export function UserCollectionListDtoFromJSON(json: any): UserCollectionListDto {
    return UserCollectionListDtoFromJSONTyped(json, false);
}

export function UserCollectionListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCollectionListDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collections': ((json['collections'] as Array<any>).map(ItemCollectionDtoFromJSON)),
    };
}

export function UserCollectionListDtoToJSON(value?: UserCollectionListDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collections': ((value.collections as Array<any>).map(ItemCollectionDtoToJSON)),
    };
}


